import { useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const policies = {
  'zh-Hant': { title:'隱私權政策', back:'← 回到 ShareGather', updated:'最後更新：2026 年 7 月 24 日', intro:'ShareGather 旨在將你想日後回看的內容保存在 iPhone 本機。本政策說明 App 如何處理這些內容。', sections:[['ShareGather 儲存的資訊','當你透過 iOS 分享選單或「Save to ShareGather」動作分享內容時，App 可能儲存你選擇分享的網址、文字和圖片；以及網址可用時的標題、描述、來源與縮圖。分類、排序、釘選設定和語言偏好也會儲存在裝置上。這些資料只用於提供保存、整理、預覽與再次分享功能。'],['沒有帳號、追蹤或雲端服務','ShareGather 不需要帳號或登入，也沒有自營伺服器或雲端儲存服務。App 不包含分析、廣告、追蹤或資料經紀整合，也不會將你的收藏傳送至 ShareGather 控制的伺服器。'],['網址預覽資料請求','對於分享的網址，ShareGather 可能使用 Apple 的 Link Presentation 請求標題或縮圖等預覽資料。這是可選的；即使預覽載入失敗，原始網址仍會被保存。網址的網站及其服務可能會收到你的網路資訊，並依其隱私政策處理該請求。'],['備份與還原','當你選擇透過系統分享選單匯出備份時，備份檔可能包含收藏項目、分類、圖片及縮圖。接收備份的 App 或服務將依其自身隱私政策處理該檔案。匯入時，ShareGather 會讀取你選擇的檔案並儲存在本機。'],['你的選擇與資料刪除','你可以刪除個別項目、分類，或使用「Clear All Saved Items」清除已儲存內容。清除後會移除項目資料及關聯的本機圖片和縮圖。移除 App 也可能移除本機資料；如需保留資料，請先匯出備份。'],['聯絡我們','若有隱私問題或意見，歡迎在 ShareGather GitHub 儲存庫提出 issue。']] },
  'zh-Hans': { title:'隐私政策', back:'← 返回 ShareGather', updated:'最后更新：2026 年 7 月 24 日', intro:'ShareGather 用于将你想日后回看的内容保存在 iPhone 本机。本政策说明 App 如何处理这些内容。', sections:[['ShareGather 储存的信息','当你通过 iOS 分享菜单或“Save to ShareGather”动作分享内容时，App 可能储存你选择分享的网址、文字和图片；以及网址可用时的标题、描述、来源与缩略图。分类、排序、置顶设置和语言偏好也会储存在设备上。这些数据只用于提供保存、整理、预览与再次分享功能。'],['没有账号、追踪或云端服务','ShareGather 不需要账号或登录，也没有自营服务器或云端储存服务。App 不包含分析、广告、追踪或数据经纪整合，也不会将你的收藏发送至 ShareGather 控制的服务器。'],['网址预览数据请求','对于分享的网址，ShareGather 可能使用 Apple 的 Link Presentation 请求标题或缩略图等预览数据。这是可选的；即使预览加载失败，原始网址仍会被保存。网址的网站及其服务可能会收到你的网络信息，并依其隐私政策处理该请求。'],['备份与恢复','当你选择通过系统分享菜单导出备份时，备份文件可能包含收藏项目、分类、图片及缩略图。接收备份的 App 或服务将依其自身隐私政策处理该文件。导入时，ShareGather 会读取你选择的文件并储存在本机。'],['你的选择与数据删除','你可以删除单个项目、分类，或使用“Clear All Saved Items”清除已保存内容。清除后会移除项目数据及关联的本机图片和缩略图。移除 App 也可能移除本机数据；如需保留数据，请先导出备份。'],['联系我们','如有隐私问题或意见，欢迎在 ShareGather GitHub 仓库提出 issue。']] },
  en: { title:'Privacy Policy', back:'← Back to ShareGather', updated:'Last updated: July 24, 2026', intro:'ShareGather is designed to save the content you want to revisit later, locally on your iPhone. This policy explains how the app handles that content.', sections:[['Information ShareGather Stores','When you share through the iOS Share Sheet or the Save to ShareGather action, the app may store the URLs, text, and images you choose to share; along with a URL’s title, description, source, and thumbnail when available. Categories, their order, pinned-item choices, and language preferences are also stored on your device. This information is used only to provide saving, organizing, previewing, and re-sharing features.'],['No Account, Tracking, or Cloud Service','ShareGather does not require an account or sign-in. It has no operated server or cloud storage service. The app contains no analytics, advertising, tracking, or data-broker integrations, and does not send your saved content to a ShareGather-controlled server.'],['URL Preview Requests','For a shared URL, ShareGather may use Apple’s Link Presentation framework to request preview metadata such as a title or thumbnail. This is optional: the original URL is saved even if preview loading fails. The linked website and its services may receive your network information and process the request under their own privacy policies.'],['Backup and Restore','When you export a backup through the system Share Sheet, the backup file may contain saved items, categories, images, and thumbnails. The app or service receiving the backup handles it under its own privacy policy. When importing, ShareGather reads the file you select and stores it locally on your device.'],['Your Choices and Data Deletion','You can delete individual items and categories, or use Clear All Saved Items to clear saved content. This removes stored item data and associated local images and thumbnails. Removing the app may also remove local data; export a backup first if you need to retain it.'],['Contact','For privacy questions or feedback, please open an issue in the ShareGather GitHub repository.']] },
}

function language() { const all = navigator.languages?.length ? navigator.languages : [navigator.language]; if (all.some(l => /zh-(hant|tw|hk|mo)/i.test(l))) return 'zh-Hant'; if (all.some(l => /^zh/i.test(l))) return 'zh-Hans'; return 'en' }
function Privacy() { const lang = language(); const p = policies[lang]; useEffect(() => { document.documentElement.lang = lang }, [lang]); return <main className="policy"><a className="brand" href="./"><img className="brand-mark" src="sharegather-icon.png" alt="" />ShareGather</a><a className="policy-back" href="./">{p.back}</a><p className="eyebrow">SHAREGATHER</p><h1>{p.title}</h1><p className="policy-updated">{p.updated}</p><p className="policy-intro">{p.intro}</p>{p.sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<p className="policy-repo"><a href="https://github.com/edward-hsu-1994/ShareGather" target="_blank" rel="noreferrer">github.com/edward-hsu-1994/ShareGather ↗</a></p></main> }
createRoot(document.getElementById('root')).render(<Privacy />)
