import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const screens = [
  ['screenshot-home.png', 'Home'], ['screenshot-save.png', 'Save to ShareGather'], ['screenshot-save-youtube.png', 'Save YouTube'], ['screenshot-category-items.png', 'Category items'], ['screenshot-item-detail.png', 'Item detail'], ['screenshot-move-items.png', 'Move items'], ['screenshot-category-reorder.png', 'Reorder categories'], ['screenshot-category-context-menu.png', 'Category menu'], ['screenshot-item-context-menu.png', 'Item menu'], ['screenshot-settings.png', 'Settings'],
]
const text = { 'zh-Hant': ['產品畫面', '看看 ShareGather 如何幫你收集、整理，再回看每一個值得保留的片刻。', '← 回到首頁'], 'zh-Hans': ['产品界面', '看看 ShareGather 如何帮你收集、整理，再回看每一个值得保留的片刻。', '← 返回首页'], en: ['Product screens', 'See how ShareGather helps you save, organize, and revisit every moment worth keeping.', '← Back home'] }
function browserLanguage() { const saved = localStorage.getItem('sharegather-language'); if (saved && text[saved]) return saved; const all = navigator.languages?.length ? navigator.languages : [navigator.language]; if (all.some(l => /zh-(hant|tw|hk|mo)/i.test(l))) return 'zh-Hant'; if (all.some(l => /^zh/i.test(l))) return 'zh-Hans'; return 'en' }
function Screenshots() { const [language, setLanguage] = useState(browserLanguage); const t = text[language]; useEffect(() => { document.documentElement.lang = language; localStorage.setItem('sharegather-language', language) }, [language]); return <main className="screens-page"><header className="screens-header"><a className="brand" href="./"><img className="brand-mark" src="sharegather-icon.png" alt="" />ShareGather</a><div className="screens-controls"><a href="./">{t[2]}</a><label className="language-picker"><span className="sr-only">Language</span><select value={language} onChange={event => setLanguage(event.target.value)} aria-label="Language"><option value="zh-Hant">繁中</option><option value="zh-Hans">简中</option><option value="en">EN</option></select></label></div></header><section className="screens-intro"><p className="eyebrow">SHAREGATHER FOR IPHONE</p><h1>{t[0]}</h1><p>{t[1]}</p></section><section className="screens-grid">{screens.map(([src, name], index) => <figure className="screen-card" key={src}><div className="screen-device"><img src={src} alt={`ShareGather — ${name}`} /></div><figcaption><span>0{index + 1}</span>{name}</figcaption></figure>)}</section></main> }
createRoot(document.getElementById('root')).render(<Screenshots />)
